[GOSSIP-63] added CRDT G-Counter implementation
apache/incubator-gossip pull request #41
Opened 2017-03-08 05:00 UTC by Mirage20

2017-03-08 13:23 UTC, edwardcapriolo requested changes

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/CrdtCounter.java
> +import java.util.Set;
Remove unused imports

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +package org.apache.gossip.crdt;
Include the apache header in all .java files

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +            }else {
Fix formatting you can use the eclipse template (XML) in the project home directory.

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +
Avoid random line breaks

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/CrdtModule.java
> +  GrowOnlyCounterMixin(@JsonProperty("myID") String myID, @JsonProperty("counters") Map<String , Long> count){ }
I do not think we should serialize myId. The reason: if one node sets myID and sends that data to another system myId is now incorrect. We need some way to properly hydrate this.

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +    public GrowOnlyCounter merge(GrowOnlyCounter other) {
For the other Crdt types they are immutable and merge returns a new instance. I would follow that pattern.

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +    public Long value() {
2 space indents

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +    private final String myID;
Comment above about myId it should be myId not myID and I think we wish it to be transient or not serialized as it crosses the wire.

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +    public void increase() {
Type should be immutable remove this.

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +    public void increaseBy(int count) {
Type should be immutable remove this.

2017-03-08 13:23 UTC, edwardcapriolo commented on src/main/java/org/apache/gossip/crdt/GrowOnlyCounter.java
> +    private GrowOnlyCounter(String myID, Map<String, Long> counters) {
I do not think we want users to manage the myId themselves. I think the interface we should provide is  a builder like OrSet

public GrowOnlyCounter(GrowOnlyCounter g, new GrowOnlyBuilder().setGosipManager(this).increment(1).decrement(3)  ){ }

With reference to GossipManager you can call gossipManager.getMyself().getId() to use as the id

2017-03-09 08:30 UTC, closed without merging

2017-03-09 08:33 UTC, Mirage20 commented
This pull request was moved to https://github.com/apache/incubator-gossip/pull/42 with updated formatting